### ISSUE TITLE
Looks good in theory…

### ISSUE THREAD

**Issue by UKenGB** [nitaybz/homebridge-yamaha-receiver#5]
Installed the plug-in, configured 3 Yamaha AVRs and they all show in Homebridge and I can turn them on and off. However, I simply cannot get them to show in HomeKit. Everything else is still working, just this plug-in's accessories will NOT show in HomeKit.

**Comment by djrobx** [comment]
Having same issue.  I figured it out... for some reason you have to manually add the accessory.   Look in homebridge log, there will be something like:

 Please add [Great Room 7523] manually in Home app. Setup Code: xxx-xx-xxxx
 
Now, manually add an accessory and choose "other options".   You'll see your AV receiver there.  Input the code and it will be addded .

**Comment by nitaybz** [comment]
seems like it's solved
